import fs from 'node:fs';
import pg from 'pg';
const env = fs.readFileSync('../../.env','utf8');
const url = env.split('\n').find(l=>l.startsWith('DATABASE_URL=')).slice('DATABASE_URL='.length).trim().replace(/^["']|["']$/g,'');
const c = new pg.Client({ connectionString: url });
await c.connect();
const q = async (s,l)=>{ try{ const r=await c.query(s); console.log(l, JSON.stringify(r.rows)); }catch(e){ console.log(l,'ERR',e.message); } };
await q("select count(*)::int n from brands","brands:");
await q("select city_id, status::text, count(*)::int n from brands group by 1,2 order by 1,2","by city/status:");
await q("select kind::text, count(*)::int n from brands group by 1","by kind:");
await q("select count(*)::int n from offices","offices:");
await q("select precision::text, count(*)::int n from offices group by 1","office precision:");
await q("select unnest(enum_range(NULL::company_kind))::text k","enum:");
await q("select count(*)::int n from company_contacts","contacts:");
await q("select count(*)::int n from field_evidence","evidence:");
await c.end();
